export enum E_ERROR {
  LOGIN_FAIL = "LOGIN_FAIL",
  REGISTER_FAIL = "REGISTER_FAIL",
  FETCH_RECIPES_FAIL = "FETCH_RECIPES_FAIL",
  CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL",
  CHANGE_EMAIL_FAIL = "CHANGE_EMAIL_FAIL",
  DELETE_USER_FAIL = "DELETE_USER_FAIL",
}
