const RecipeActionTypes = {
  ADD_RECIPE: "ADD_RECIPE",
  REMOVE_RECIPE: "REMOVE_RECIPE",
  UPDATE_RECIPE: "UPDATE_RECIPE",
  GET_RECIPES: "GET_RECIPES",
  CLEAR_RECIPES: "CLEAR_RECIPES",
  SET_RECIPE_FOR_DISPLAY: "SET_RECIPE_FOR_DISPLAY",
  CLEAR_RECIPE_TO_DISPLAY: "CLEAR_RECIPE_TO_DISPLAY",
};

export default RecipeActionTypes;
