const UiActionTypes = {
  SET_LOADING: "SET_LOADING",
  STOP_LOADING: "STOP_LOADING",
  SET_SEARCH_FILED: "SET_SEARCH_FILED",
  SET_FILTER_TAGS: "SET_FILTER_TAGS",
  CLEAR_FILTERS: "CLEAR_FILTERS",
};

export default UiActionTypes;
